### ISSUE TITLE
Configuration settings to allow remote run

### ISSUE THREAD

**Issue by tflecht** [leinardi/pylint-pycharm#36]
**Is your feature request related to a problem? Please describe.**
I run pycharm on my OSX machine, running a remote interpreter running in a Vagrant guest OS. I would also like pycharm to run pylint in that guest OS.

**Describe the solution you'd like**
A setting analogous to the remote interpreter setting in pycharm. Maybe the pylint-pycharm plugin could even infer it should run there, based on the Project Interpreter setting? But I'd be really happy with any way to configure this.

**Describe alternatives you've considered**
I tried to figure out how to run an external remote ssh command invoking pylint in the guest OS, but I think I then lose the really nice visual indication of linting issues, and the ability to run Pylint from the IDE by clicking a button.

**Additional context**
NA

**Comment by OrDuan** [comment]
I'm having the same issue, but using Docker.
Would be great to see support for that since more and more people in big teams using docker/vagrant setups. Thanks :)

**Comment by hmoravec** [comment]
I also agree this is an important feature as a typical user of Pylint is a professional developer who also uses Docker/Vagrant for development environment. It would be nice if it would be at least possible to use Pylint executable for environment that is different than the project environment.

**Comment by luke-1993** [comment]
@tflecht - is this feature now available? I see you've marked it as completed. I'm running a project with a remote ssh interpetter configured in pycharm. When I attempt to scan my project with pylint, I get:

![image](https://user-images.githubusercontent.com/14069946/193559939-8423db5b-435c-43a6-ae0d-95c67f851340.png)

I have the pylint executable configured to point at the pylint binary on my local machine which is passing the test:

![image](https://user-images.githubusercontent.com/14069946/193560125-9985fa43-6367-4ac6-bef2-98b2766319c0.png)


I suspect pylint plugin is getting confused due to using a remote ssh python interpreter
